[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "quipu-engine"
version = "0.1.0"
authors = [
  { name="doux", email="douxldh@gmail.com" },
]
description = "The state and history engine for Quipu, powered by Git plumbing."
requires-python = ">=3.8"
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "quipu-interfaces",
    "pyyaml>=6.0",
]

[tool.uv.sources]
quipu-interfaces = { workspace = true }

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true